name: "Testing"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'
    - name: install golint
      run: go get -u golang.org/x/lint/golint
    - name: static code analyse
      run: go vet ./...
    - name: check lint
      run: golint ./...
    - name: tests
      run: go test ./...


